version: '3.8'

services:
  portfolio-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "8080:8080"
    environment:
      # OpenAI API configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL:-https://api.openai.com/v1/chat/completions}
      # Quarkus configuration
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=8080
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
